version: '3.9'
services:
  job-scraper-api:
    build:
      context: .  
      dockerfile: ./JobScraper.API/Dockerfile    
    image: job-scraper-api
    ports:
      - "8080:80"            
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=host.docker.internal;Database=JobScraper;Username=postgres;Password=postgres
    volumes:
      - ./JobScraper.API:/src
