version: '3.9'

services:
  job-scraper-api:
    build:
      context: .
      dockerfile: ./JobScraper.API/Dockerfile
    image: job-scraper-api
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=job-scraper-db;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASS}
    depends_on:
      - job-scraper-db

  job-scraper-db:
    image: postgres:14
    container_name: job-scraper-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

