apiVersion: v1
kind: Service
metadata:
  name: job-scraper-api-service
spec:
  selector:
    app: job-scraper-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
