apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-scraper-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: job-scraper-api
  template:
    metadata:
      labels:
        app: job-scraper-api
    spec:
      containers:
      - name: job-scraper-api
        image: job-scraper-api:latest
        ports:
        - containerPort: 80
