name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up .NET Core
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0
    

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore
      working-directory: JobScraper.API

    # Build the solution
    - name: Build
      run: dotnet build --no-restore
      working-directory: JobScraper.API

    # Run tests
    - name: Run tests
      run: dotnet test --no-build --verbosity normal
      working-directory: JobScraper.Tests
