name: Deploy to EC2

on:
  push:
    branches:
      - main   # ✅ 你可以改成你部署用的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "$EC2_KEY" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem $EC2_HOST << 'EOF'
            cd ~/JobScraper || exit 1

            echo "Pulling latest code..."
            git pull origin main

            echo "Building and starting containers..."
            docker-compose -f docker-compose.override.production.yml up -d --build
          EOF
        env:
          EC2_KEY: ${{ secrets.EC2_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
